### ISSUE TITLE
Visualize an Graph Alignment with -v 

### ISSUE THREAD

**Issue by ck17byqe** [mk36fyvy/multivitamin#18]
When i try to visualize the output of an graph alignment with -v ...
------->multiVitamin -a subVF2 -i graph/4.2.1.1.graph graph/4.2.1.10.graph  -o 1_und_10
... the output is not readable. But when i delete all "_" "°" and ":" signs the output is perfect readable. 

For Pictures see: https://github.com/jw44lavo/graphen/tree/chrissi/Bug_Mulitvitamin

**Comment by mk36fyvy** [comment]
Unfortunately, I could not reproduce the error. You might want to pull the newest version, maybe reinstall the package and realign your graphs. 

If this does not resolve the issue, maybe looking at the exact visualization command or the graph file might help.

**Comment by mk36fyvy** [comment]
Issue has been solved by pulling the newest version.
